name: Your New Jekyll Site
pygments: true
assets:
  compress:
    css:  sass
    js:   uglifier
navigation:
-   text: home
    url: /
    subnav:
        -   text: audience
        -   text: information
        -   text: communicate
-   text: inspiration
    url: /inspiration/roomcast
-   text: survey
    url: /survey
-   text: about us    
    url: /about
